### ISSUE TITLE
add optional style= param, use to output <link>/<style> stylesheet when ashtml=1 

### ISSUE THREAD

**Issue by tantek** [dissolve/socialstream#10]
Currently stream.thatmustbe.us has a wonderful jf2 to mf2 converter that provides nice markup output, e.g.:

http://stream.thatmustbe.us/?url=https%3A%2F%2Fwebmention.io%2Fapi%2Flinks.jf2%3Ftarget%3Dhttp%3A%2F%2Ftantek.com%2F2017%2F183%2Fe1%2Fsunday-yoga-presidio&op=jf2-mf2&ashtml=1

Proposed new "style=" param (in addition to the url, op, ashtml params in the above URL), that takes *either* a URL to a style sheet (e.g. style=https://example.com/ext.css ) or an inline stylesheet (e.g. style=img{height:2em;} ) - with proper URL escaping of course for the param values. And then adds to the HTML output accordingly e.g.:
&lt;link rel="stylesheet" href="https://example.com/ext.css" /&gt; [aside wow GHmd is quirky, somehow treats a link tag as markup, but HTML-escapes the style tag below?]
or
<style>img{height:2em;}</style>

Use-case: this would (likely) enable iframe embedding of the stream thatmustbe us URL with CSS from the embedder to match the rest of the styling of context around the iframe (e.g. a permalink to an event post).

For now only accept URL param for "style=" that starts with http: or https: - that's good enough for the 99% case, else put contents inside a <style> ... </style> element.

**Comment by dissolve** [comment]
this has been added in the latest commits

**Comment by tantek** [comment]
Works!
