### ISSUE TITLE
default markup: base target=_top for links in case framed

### ISSUE THREAD

**Issue by tantek** [dissolve/socialstream#14]
The default document markup returned should include a:

```<base target="_top" />``` inside the HEAD element.

so that if the results are iframed, e.g. like RSVPs on my indie events like http://tantek.com/2017/277/e1/homebrew-website-club then clicking on any of the links will navigate the top browser context instead of navigating inside the iframe which is in general poor UX.

**Comment by Zegnat** [comment]
Wouldn’t `_parent` be better?

It sounds like you would want it to break out of your specific iframe, not all frames that might exist. That would allow me to put tantek.com in a frame on my site without the RSVP links breaking the frame I want to exist.

**Comment by tantek** [comment]
I'm ok with _parent and willing to try that to see how it works. I still prefer _top as I think navigation *inside* a frame is still a really bad / confusing navigation user experience, with history, etc.
