### ISSUE TITLE
Switch ActivityStreams namespace -> ActivityStreams context

### ISSUE THREAD

**Issue by cwebber** [dissolve/socialstream#5]
Switch to "http://www.w3.org/TR/activitystreams-core/activitystreams2-context.jsonld"

**Comment by dissolve** [comment]
Just to be clear this would mean that any terms not found in the jf2 context fall back to looking for those in AS2 (which it turn I believe falls back to AS1)?

also, would it be "http://www.w3.org/TR/activitystreams-core/activitystreams2-context" ?  Is there a difference?

**Comment by dissolve** [comment]
also, would it be "http://www.w3.org/TR/activitystreams-core/activitystreams2-context" ?

**Comment by cwebber** [comment]
Your link is probably the right one, yes.  And yes, this should make it so that it falls back to searching the AS2 context.

(AS2's context doesn't fall back to AS1 afaik, but I could be wrong....)

**Comment by dissolve** [comment]
@cwebber fixed on new repo
